<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>test generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="test, WOW Slider, HTML5 Slider, Responsive Slider" />
	<meta name="description" content="test created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="slider/engine1/style.css" />
	<script type="text/javascript" src="slider/engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#d7d7d7" >
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="slider/data1/images/nacoss.jpg" alt="Desert" title="Nacoss Exco" id="wows1_1"/>Nacoss Exco</li>

<li><img src="slider/data1/images/gate.jpg" alt="Desert" title="OGITECH Main Gate" id="wows1_1"/>OGITEC Main Gate</li>
<li><img src="slider/data1/images/ict.jpg" alt="Desert" title="ICT" id="wows1_1"/>ICT</li>
<li><img src="slider/data1/images/rector.jpg" alt="Desert" title="Rector" id="wows1_1"/>Rector</li>
</ul></div>
<div class="ws_bullets" ><div>
<a href="#" title="Nacoss Excos"><img src="slider/data1/tooltips/nacoss.jpg" alt="Nacoss Exco"/>1</a>
<a href="#" title="OGITECH Main Gate"><img src="slider/data1/tooltips/gate.jpg" alt="OGITECH Main Gate"/>2</a>
<a href="#" title="ICT"><img src="slider/data1/tooltips/ict.jpg" alt="ICT"/>3</a>
<a href="#" title="Rector"><img src="slider/data1/tooltips/rector.jpg" alt="Rector"/>4</a>

</div></div>
<span class="wsl"><a href="http://wowslider.com">HTML Slider</a> by WOWSlider.com v4.1</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="slider/engine1/wowslider.js"></script>
	<script type="text/javascript" src="slider/engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>